### ISSUE TITLE
NullPointerException in StringTypeTag$.typeToString(StringTypeTag.scala:27)

### ISSUE THREAD

**Issue by xuwei-k** [sbt/util#119]
nondeterministic failure 🤔 

```bash
git clone https://github.com/unfiltered/unfiltered.g8.git
cd unfiltered.g8
git checkout 56d8b7cac678e869fa5da89323bf29f988f0296f
sbt ';set g8Properties in g8 in Test ~= { _ ++ Map(("scala_version" -> "2.10.6"), ("sbt_version" -> "1.0.0")) }; g8Test'
```

- https://github.com/unfiltered/unfiltered.g8/tree/56d8b7cac678e869fa5da89323bf29f988f0296f
- https://travis-ci.org/unfiltered/unfiltered.g8/jobs/264319172#L1044
- https://github.com/sbt/util/blob/v1.0.0/internal/util-logging/src/main/scala/sbt/internal/util/ManagedLogger.scala#L45

```
[info] [error] java.lang.NullPointerException
[info] [error] 	at sbt.internal.util.StringTypeTag$.typeToString(StringTypeTag.scala:27)
[info] [error] 	at sbt.internal.util.StringTypeTag$.apply(StringTypeTag.scala:15)
[info] [error] 	at sbt.internal.util.ManagedLogger.registerStringCodec(ManagedLogger.scala:39)
[info] [error] 	at sbt.internal.util.ManagedLogger.<init>(ManagedLogger.scala:45)
[info] [error] 	at sbt.util.LogExchange.logger(LogExchange.scala:32)
[info] [error] 	at sbt.internal.LogManager$.defaultLogger(LogManager.scala:122)
[info] [error] 	at sbt.internal.LogManager$DefaultLogManager.apply(LogManager.scala:99)
[info] [error] 	at sbt.internal.LogManager$.$anonfun$construct$1(LogManager.scala:47)
[info] [error] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:173)
[info] [error] 	at sbt.std.TaskStreams.log(Streams.scala:88)
[info] [error] 	at sbt.std.TaskStreams.log$(Streams.scala:88)
[info] [error] 	at sbt.std.Streams$$anon$3$$anon$2.log$lzycompute(Streams.scala:137)
[info] [error] 	at sbt.std.Streams$$anon$3$$anon$2.log(Streams.scala:137)
[info] [error] 	at sbt.Defaults$.$anonfun$compileInputsSettings$2(Defaults.scala:1434)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[info] [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[info] [error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[info] [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[info] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
[info] [error] 	at sbt.Execute.work(Execute.scala:266)
[info] [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[info] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[info] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[info] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[info] [error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[info] [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[info] [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[info] [error] 	at java.lang.Thread.run(Thread.java:748)
[info] [error] (test:compile::compilerReporter) java.lang.NullPointerException
[info] [error] Total time: 27 s, completed Aug 14, 2017 11:12:35 AM
```

**Comment by eed3si9n** [comment]
I've seen the NPE happen too, but I can't seem to reproduce it using `unfiltered/unfiltered.g8` or by making the loggers in thread - https://github.com/sbt/util/compare/1.x...eed3si9n:wip/npe?expand=1
