### ISSUE TITLE
A hidden file is included as a scripted test

### ISSUE THREAD

**Issue by gkossakowski** [sbt/util#36]
I've got a failure like this:

```
sbt.internal.io.ResourcesException: Resource directory '.DS_Store' in group 'source-dependencies' not found.
    at sbt.internal.io.Resources$.error(Resources.scala:25)
    at sbt.internal.io.Resources.readOnlyResourceDirectory(Resources.scala:41)
    at sbt.internal.io.Resources.readWriteResourceDirectory(Resources.scala:47)
    at sbt.internal.scripted.ScriptedTests$$anonfun$scriptedTest$2$$anonfun$apply$2$$anonfun$apply$3.apply(ScriptedTests.scala:59)
    at sbt.internal.scripted.ScriptedTests$$anonfun$scriptedTest$2$$anonfun$apply$2$$anonfun$apply$3.apply(ScriptedTests.scala:57)
    at sbt.internal.scripted.ScriptedRunnerImpl$$anonfun$2.apply(ScriptedTests.scala:23)
    at sbt.internal.scripted.ScriptedRunnerImpl$$anonfun$2.apply(ScriptedTests.scala:23)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
    at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
    at sbt.internal.scripted.ScriptedRunnerImpl$.runAll(ScriptedTests.scala:23)
    at sbt.internal.scripted.ScriptedRunnerImpl$.run(ScriptedTests.scala:20)
    at sbt.internal.inc.IncScriptedRunner.run(IncScriptedRunner.scala:11)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at Scripted$.doScripted(Scripted.scala:74)
    at $0e73639291fc1196c7f3$$anonfun$scriptedTask$2$$anonfun$apply$6$$anonfun$apply$7.apply(build.sbt:264)
    at $0e73639291fc1196c7f3$$anonfun$scriptedTask$2$$anonfun$apply$6$$anonfun$apply$7.apply(build.sbt:261)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (zincRoot/*:scripted) sbt.internal.io.ResourcesException: Resource directory '.DS_Store' in group 'source-dependencies' not found.
[error] Total time: 2 s, completed Apr 7, 2016 12:01:20 PM
```

The implementation tries to filter out hidden files already:

``` scala
final class ListTests(baseDirectory: File, accept: ScriptedTest => Boolean, log: Logger) {
  def filter = DirectoryFilter -- HiddenFileFilter
```

but it doesn't work.

**Comment by mrveera** [comment]
Please refer this sbt/io#22 , I don't think it is a bug from util
